### ISSUE TITLE
Modpack Crashing when loading with Extra Little Tiles

### ISSUE THREAD

**Issue by EmeraldTiger64** [Doc-1/LTPhoto#11]
Hello. I am looking forward to using this mod in an upcoming server project with some friends, but I am having one issue. When loading the modpack, this mod crashes the game. I have posted the crash log at the link here: https://paste.ee/p/B2MnQ

I am running Minecraft Version 1.12.2, with Forge version 14.23.5.2847.

If you are able to help with this issue, then thank you.

**Comment by brisingraerowing** [comment]
Known issue with the latest LT version. Hopefully will be fixed soon.

**Comment by EmeraldTiger64** [comment]
Ok. Thank you.
