### ISSUE TITLE
ALET (LTPhoto) 1.0.10 Tape Measure crashes the world

### ISSUE THREAD

**Issue by SrBits** [Doc-1/LTPhoto#13]
Hello there. 
I instaled A Little Extra Tiles mod addon to help me with a building project I have been working on with Little Tiles. Unfortunately, in a certain moment when I hold the tape measure the game crashed by an unknown reasson for me. I can't join back the world because it keeps crashing while it is still loading the player holding the tape. This problem didn't happen in last times when I used the tape and I don't know what exactly caused it.

The following images bellow show the crash report. The instaled mod FPSReducer it's necessary for dealing with another issue involving game freeze.

![image](https://user-images.githubusercontent.com/51025489/99245702-cb30d780-27e2-11eb-9e81-63576b50c55a.png)

![image](https://user-images.githubusercontent.com/51025489/99245770-eac80000-27e2-11eb-8c42-b9603d849463.png)

If you could help me I would really thank you and be able continue my project.

**Comment by Doc-1** [comment]
My apologies for the late reply. Not used to people actually using GitHub to report issues. 
Did you have a tape measure before updating to 1.0.10? And once you joined after you held the tape measure and looked at something you crashed?
If so, it should be an easy fix. I neglected to check for a null as I didn't think I would need to. Will post a possible fix sometime today or tomorrow.

**Comment by Doc-1** [comment]
Looks like it is going to take a bit longer to post the update. Curse Forge is taking a while to approve it.

**Comment by Doc-1** [comment]
Alright, it is now available. Once you have tried it, could you let me know if it was successful?
https://www.curseforge.com/minecraft/mc-mods/alet/files/3127616

**Comment by SrBits** [comment]
> Alright, it is now available. Once you have tried it, could you let me know if it was successful?
> https://www.curseforge.com/minecraft/mc-mods/alet/files/3127616

Thanks for the link, I'll try use it later on. I solved it by removing the mod so the tape disapears, but I'm not quite sure what caused it in the first place.

Also, if somehow involved, my game have been crashing when I when minimize it. I talked to the original Little Tiles creator about it but it seems if affects other mods too. That haven't happen since that, so I imagine it can be either something that happened to my computer or the mods did somethng.
(I forgot to mention that to solve this crashing I use the FpsReducer mod.

**Comment by SrBits** [comment]
I am playing this newest version of the mod, and it's working! Thanks! If some other bug happen I will report it in other time, so I'll close this issue. About the game freezing, I don't think I'll get a real solution for it soon while still needing to use the FpsReducer mod, but in case, you could look for it. Again: Thank you.
