### ISSUE TITLE
[SUGGESTION] Increase Character Limit on the Photo Importer Text Box

### ISSUE THREAD

**Issue by Archilyte** [Doc-1/LTPhoto#16]
Title says it all. 

I am suggesting this because I had an issue where the Photo Importer generating crash files when pressed Print. (I pasted the picture file path, but the character limit cut the end of it off.)

**Comment by Doc-1** [comment]
Hello, 
Sorry for now just reading your message. I've extended the max chars from 1000 to 2048. Hopefully, that'll be enough.
https://www.curseforge.com/minecraft/mc-mods/alet/files/3213485
