### ISSUE TITLE
Crash on world load with Aether 2 Highlands

### ISSUE THREAD

**Issue by Vodulm** [Doc-1/LTPhoto#17]
After installing your mod, when trying to open an existing world in which Aether dimension was loaded at least once - it crashes.
New worlds doesnt seem to crash.
[crash-2020-12-28_20.51.17-server.txt](https://github.com/Doc-1/A-Little-Extra-Tiles/files/5808344/crash-2020-12-28_20.51.17-server.txt)

**Comment by Doc-1** [comment]
Hello,
Sorry for the late response. Looking at the crash report I do not see any correlation of A little extra tiles causing this crash. Sometime this week I'll download Aether 2 and try to replicate the crash. Just wanted to let you know as you posted this a while ago.
Thank you,
_Doc
