### ISSUE TITLE
"No Class Default Found" error crashing the game

### ISSUE THREAD

**Issue by JadianRadiator** [Doc-1/LTPhoto#19]
I'm crashing with a "No Class Default Found" from the class path of the Tape Measure item.
Curseforge pack profile export so I can lazy the mod list - [Economica-No_Def_Class_Crash.zip](https://github.com/Doc-1/A-Little-Extra-Tiles/files/6984973/Economica-No_Def_Class_Crash.zip)
Crash Log - [crash-2021-08-13_14.38.28-client.txt](https://github.com/Doc-1/A-Little-Extra-Tiles/files/6984976/crash-2021-08-13_14.38.28-client.txt)

**Comment by brisingraerowing** [comment]
You are majorly out of date. The latest LT version is 1.5.24. Pre 199_73 is almost a year old now.

Also, The 'Def' in 'NoClassDefFoundError' means Definition, not Default.

**Comment by JadianRadiator** [comment]
if you had looked at the date, 1.5.24 was released _after_ this issue was originally opened.
I'll try it again now that it's been updated so much.
Not sure why Github took so long to give me a notification.
