### ISSUE TITLE
Signal Converter won't accept some redstone components

### ISSUE THREAD

**Issue by whatsapp2** [Doc-1/LTPhoto#23]
Not sure if it's an ALET bug or LT bug, but currently Signal Converter won't accept redstone input from redstone components (like repeaters, levers, redstone torches...) except for redstone dust and redstone blocks
![2023-06-01_19 08 11](https://github.com/Doc-1/A-Little-Extra-Tiles/assets/25994176/7be25901-f080-4473-97a8-a95c0bd27fef)
I'm using:
- CreativeCore version: CreativeCore_v1.10.70_mc1.12.2
- Little Tiles version: LittleTiles_v1.5.72_mc1.12.2
- ALET version: A+Little+Extra+Tiles-1.1.0-pre014

**Comment by Doc-1** [comment]
Sorry for not noticing your post. Yes, that is an LT issue. If I get time, I will look into it.
