### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by whatsapp2** [Doc-1/LTPhoto#24]
First suggestion is to make a separate function for the Tape Measure capable of measuring the "real" distance between 2 points. 

The current Line function in the Tape Measure seems to show distance based on block position, which is not exactly ideal for making geometric patterns, or measure distances when working with angled structures.

![2023-07-03_00 35 25](https://github.com/Doc-1/A-Little-Extra-Tiles/assets/25994176/f1d65e15-9295-4a23-9f93-d3bf38c2266d)

In this example, the Line function shows the distance as 1 block, which is just an approximation of the real length. The suggested function would show an approximation based off the "real" length using the pythagorean theorem [c=√a²+b²], which should be √2 ≈ 1.412 blocks or around 1 block and 7/16 tiles (closest approximation using 16 grid) 

** **

Second suggestion is to make a new block or new function inside one of the existing machines to allow rotation of structures. 

Right now it's almost impossible to rotate massive and laggy structures using the arrow keys, it just doesn't want to work. 

![2023-07-03_01 02 17](https://github.com/Doc-1/A-Little-Extra-Tiles/assets/25994176/4fee3408-abac-47e7-8ce2-ff2745882bba)

Here for example I'm trying to rotate a 160k structure 90 degrees to the right, but because fps dropped from 60 to just 3, the structure won't rotate using arrow keys. Suggestion would allow me to insert this structure in an input slot, then I could select how many degrees I want the structure to be rotated at (90º,180º,270º,360º to the left or right) and finally after hitting the "print" button, the machine would output the same structure but rotated by how many degrees were previously selected.

**Comment by Doc-1** [comment]
Press C, click the "tile," and select a real-world measurement. As for the rotation of large structures, it feels too specific for me to implement. If I do get time, I might add something for that.
